name: Hello Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: hello world
        run: echo "Hello World"
        shell: bash
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: greet world
        run: echo "greeting world"
        shell: bash

